language: generic
sudo: required
services:
  - docker

before_install: 
  -docker build -t georgejuliet/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true georgejuliet/docker-react npm run test